"""add parliamentarian to videos_audios

Revision ID: a18f82537ce9
Revises: b656da2ce085
Create Date: 2025-11-24 16:05:30.179417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a18f82537ce9'
down_revision: Union[str, None] = 'b656da2ce085'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos_audios', sa.Column('parliamentarian_id', sa.BigInteger(), nullable=False))
    op.create_foreign_key(None, 'videos_audios', 'parliamentarian', ['parliamentarian_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'videos_audios', type_='foreignkey')
    op.drop_column('videos_audios', 'parliamentarian_id')
    # ### end Alembic commands ###
