"""create initial tables

Revision ID: b656da2ce085
Revises: 
Create Date: 2025-11-24 15:55:22.061610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b656da2ce085'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agency',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('agency_code', sa.BigInteger(), nullable=True),
    sa.Column('agency_type_code', sa.Text(), nullable=True),
    sa.Column('agency_type', sa.Text(), nullable=True),
    sa.Column('acronym', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('alias', sa.Text(), nullable=True),
    sa.Column('publication_name', sa.Text(), nullable=True),
    sa.Column('short_name', sa.Text(), nullable=True),
    sa.Column('uri', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agency_id'), 'agency', ['id'], unique=False)
    op.create_table('committee',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('committee_code', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('acronym', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_committee_id'), 'committee', ['id'], unique=False)
    op.create_table('parliamentarian',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('parliamentarian_code', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('full_name', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('telephone', sa.Text(), nullable=True),
    sa.Column('cpf', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('party', sa.Text(), nullable=True),
    sa.Column('state_of_birth', sa.Text(), nullable=True),
    sa.Column('city_of_birth', sa.Text(), nullable=True),
    sa.Column('state_elected', sa.Text(), nullable=True),
    sa.Column('site', sa.Text(), nullable=True),
    sa.Column('education', sa.Text(), nullable=True),
    sa.Column('office_name', sa.Text(), nullable=True),
    sa.Column('office_building', sa.Text(), nullable=True),
    sa.Column('office_number', sa.Text(), nullable=True),
    sa.Column('office_floor', sa.Text(), nullable=True),
    sa.Column('office_email', sa.Text(), nullable=True),
    sa.Column('biography_link', sa.Text(), nullable=True),
    sa.Column('biography_text', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parliamentarian_id'), 'parliamentarian', ['id'], unique=False)
    op.create_table('proposition_status',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('proposition_status_code', sa.Text(), nullable=True),
    sa.Column('acronym', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposition_status_id'), 'proposition_status', ['id'], unique=False)
    op.create_table('proposition_type',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('proposition_type_code', sa.Text(), nullable=True),
    sa.Column('acronym', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposition_type_id'), 'proposition_type', ['id'], unique=False)
    op.create_table('social_network',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_network_id'), 'social_network', ['id'], unique=False)
    op.create_table('videos_audios',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('hour_minute', sa.Text(), nullable=True),
    sa.Column('place', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_videos_audios_id'), 'videos_audios', ['id'], unique=False)
    op.create_table('committee_attendance',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('parliamentarian_id', sa.BigInteger(), nullable=False),
    sa.Column('committee_id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('link', sa.Text(), nullable=True),
    sa.Column('frequency', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['committee_id'], ['committee.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parliamentarian_id'], ['parliamentarian.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_committee_attendance_id'), 'committee_attendance', ['id'], unique=False)
    op.create_table('parliamentarian_social_network',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('parliamentarian_id', sa.BigInteger(), nullable=False),
    sa.Column('social_network_id', sa.BigInteger(), nullable=False),
    sa.Column('profile_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parliamentarian_id'], ['parliamentarian.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['social_network_id'], ['social_network.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parliamentarian_social_network_id'), 'parliamentarian_social_network', ['id'], unique=False)
    op.create_table('plenary_attendance',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('parliamentarian_id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('session_attendance', sa.Text(), nullable=True),
    sa.Column('daily_attendance_justification', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parliamentarian_id'], ['parliamentarian.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plenary_attendance_id'), 'plenary_attendance', ['id'], unique=False)
    op.create_table('proposition',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('proposition_code', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('link', sa.Text(), nullable=True),
    sa.Column('proposition_acronym', sa.Text(), nullable=True),
    sa.Column('proposition_number', sa.Integer(), nullable=True),
    sa.Column('presentation_year', sa.Integer(), nullable=True),
    sa.Column('agency_id', sa.BigInteger(), nullable=True),
    sa.Column('proposition_type_id', sa.BigInteger(), nullable=True),
    sa.Column('proposition_status_id', sa.BigInteger(), nullable=True),
    sa.Column('current_status', sa.Text(), nullable=True),
    sa.Column('proposition_description', sa.Text(), nullable=True),
    sa.Column('presentation_date', sa.Date(), nullable=True),
    sa.Column('presentation_month', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agency.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['proposition_status_id'], ['proposition_status.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['proposition_type_id'], ['proposition_type.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposition_id'), 'proposition', ['id'], unique=False)
    op.create_table('speeches_transcripts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('parliamentarian_id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('session_number', sa.Text(), nullable=True),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('speech_link', sa.Text(), nullable=True),
    sa.Column('speech_text', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('hour_minute', sa.Text(), nullable=True),
    sa.Column('publication_link', sa.Text(), nullable=True),
    sa.Column('publication_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parliamentarian_id'], ['parliamentarian.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_speeches_transcripts_id'), 'speeches_transcripts', ['id'], unique=False)
    op.create_table('authors_proposition',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('parliamentarian_id', sa.BigInteger(), nullable=False),
    sa.Column('proposition_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parliamentarian_id'], ['parliamentarian.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proposition_id'], ['proposition.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authors_proposition_id'), 'authors_proposition', ['id'], unique=False)
    op.create_table('roll_call_votes',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('parliamentarian_id', sa.BigInteger(), nullable=False),
    sa.Column('proposition_id', sa.BigInteger(), nullable=False),
    sa.Column('vote', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('link', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parliamentarian_id'], ['parliamentarian.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proposition_id'], ['proposition.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roll_call_votes_id'), 'roll_call_votes', ['id'], unique=False)
    op.create_table('speeches_transcripts_proposition',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('speeches_transcripts_id', sa.BigInteger(), nullable=False),
    sa.Column('proposition_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['proposition_id'], ['proposition.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['speeches_transcripts_id'], ['speeches_transcripts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_speeches_transcripts_proposition_id'), 'speeches_transcripts_proposition', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_speeches_transcripts_proposition_id'), table_name='speeches_transcripts_proposition')
    op.drop_table('speeches_transcripts_proposition')
    op.drop_index(op.f('ix_roll_call_votes_id'), table_name='roll_call_votes')
    op.drop_table('roll_call_votes')
    op.drop_index(op.f('ix_authors_proposition_id'), table_name='authors_proposition')
    op.drop_table('authors_proposition')
    op.drop_index(op.f('ix_speeches_transcripts_id'), table_name='speeches_transcripts')
    op.drop_table('speeches_transcripts')
    op.drop_index(op.f('ix_proposition_id'), table_name='proposition')
    op.drop_table('proposition')
    op.drop_index(op.f('ix_plenary_attendance_id'), table_name='plenary_attendance')
    op.drop_table('plenary_attendance')
    op.drop_index(op.f('ix_parliamentarian_social_network_id'), table_name='parliamentarian_social_network')
    op.drop_table('parliamentarian_social_network')
    op.drop_index(op.f('ix_committee_attendance_id'), table_name='committee_attendance')
    op.drop_table('committee_attendance')
    op.drop_index(op.f('ix_videos_audios_id'), table_name='videos_audios')
    op.drop_table('videos_audios')
    op.drop_index(op.f('ix_social_network_id'), table_name='social_network')
    op.drop_table('social_network')
    op.drop_index(op.f('ix_proposition_type_id'), table_name='proposition_type')
    op.drop_table('proposition_type')
    op.drop_index(op.f('ix_proposition_status_id'), table_name='proposition_status')
    op.drop_table('proposition_status')
    op.drop_index(op.f('ix_parliamentarian_id'), table_name='parliamentarian')
    op.drop_table('parliamentarian')
    op.drop_index(op.f('ix_committee_id'), table_name='committee')
    op.drop_table('committee')
    op.drop_index(op.f('ix_agency_id'), table_name='agency')
    op.drop_table('agency')
    # ### end Alembic commands ###
