"""add projects, tiers e favoritos de parlamentares

Revision ID: d2d4b6c7a3e1
Revises: a18f82537ce9
Create Date: 2026-02-25 10:15:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d2d4b6c7a3e1"
down_revision: Union[str, None] = "a18f82537ce9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tiers",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("tier_name_debug", sa.Text(), nullable=False),
        sa.Column("product_id", sa.Text(), nullable=False),
        sa.Column(
            "detalhes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("product_id"),
    )
    op.create_index(op.f("ix_tiers_id"), "tiers", ["id"], unique=False)

    op.create_table(
        "projetos",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("nome", sa.Text(), nullable=False),
        sa.Column("cliente", sa.Text(), nullable=True),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("tier_id", sa.BigInteger(), nullable=True),
        sa.Column("tag_ghost", sa.Text(), nullable=True),
        sa.Column(
            "qtd_termos",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["tier_id"],
            ["tiers.id"],
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email", name="uq_projetos_email"),
    )
    op.create_index(op.f("ix_projetos_id"), "projetos", ["id"], unique=False)
    op.create_index("ix_projetos_email", "projetos", ["email"], unique=True)
    op.create_index(
        "ix_projetos_tier_id",
        "projetos",
        ["tier_id"],
        unique=False,
    )

    op.create_table(
        "projetos_parliamentarian",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("projeto_id", sa.BigInteger(), nullable=False),
        sa.Column("parliamentarian_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["parliamentarian_id"],
            ["parliamentarian.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["projeto_id"],
            ["projetos.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "projeto_id",
            "parliamentarian_id",
            name="uq_projeto_parliamentarian_unique",
        ),
    )
    op.create_index(
        op.f("ix_projetos_parliamentarian_id"),
        "projetos_parliamentarian",
        ["id"],
        unique=False,
    )
    op.create_index(
        "ix_projetos_parliamentarian_projeto_id",
        "projetos_parliamentarian",
        ["projeto_id"],
        unique=False,
    )
    op.create_index(
        "ix_projetos_parliamentarian_parliamentarian_id",
        "projetos_parliamentarian",
        ["parliamentarian_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_projetos_parliamentarian_parliamentarian_id",
        table_name="projetos_parliamentarian",
    )
    op.drop_index(
        "ix_projetos_parliamentarian_projeto_id",
        table_name="projetos_parliamentarian",
    )
    op.drop_index(
        op.f("ix_projetos_parliamentarian_id"),
        table_name="projetos_parliamentarian",
    )
    op.drop_table("projetos_parliamentarian")
    op.drop_index("ix_projetos_tier_id", table_name="projetos")
    op.drop_index("ix_projetos_email", table_name="projetos")
    op.drop_index(op.f("ix_projetos_id"), table_name="projetos")
    op.drop_table("projetos")
    op.drop_index(op.f("ix_tiers_id"), table_name="tiers")
    op.drop_table("tiers")
    # ### end Alembic commands ###

