"""add tables for speech keywords and entities

Revision ID: f3b0b7f2c4d1
Revises: d2d4b6c7a3e1
Create Date: 2026-03-11 14:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f3b0b7f2c4d1"
down_revision: Union[str, None] = "d2d4b6c7a3e1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "speeches_transcripts_keywords",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("speeches_transcripts_id", sa.BigInteger(), nullable=False),
        sa.Column("keyword", sa.Text(), nullable=False),
        sa.Column("term", sa.Text(), nullable=False),
        sa.Column("frequency", sa.Integer(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column(
            "is_primary",
            sa.Boolean(),
            server_default=sa.false(),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["speeches_transcripts_id"],
            ["speeches_transcripts.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_speeches_transcripts_keywords_id"),
        "speeches_transcripts_keywords",
        ["id"],
        unique=False,
    )
    op.create_index(
        "ix_speeches_transcripts_keywords_speech_id",
        "speeches_transcripts_keywords",
        ["speeches_transcripts_id"],
        unique=False,
    )

    op.create_table(
        "speeches_transcripts_entities",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("speeches_transcripts_id", sa.BigInteger(), nullable=False),
        sa.Column("label", sa.Text(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("start_char", sa.Integer(), nullable=True),
        sa.Column("end_char", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["speeches_transcripts_id"],
            ["speeches_transcripts.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_speeches_transcripts_entities_id"),
        "speeches_transcripts_entities",
        ["id"],
        unique=False,
    )
    op.create_index(
        "ix_speeches_transcripts_entities_speech_id",
        "speeches_transcripts_entities",
        ["speeches_transcripts_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_speeches_transcripts_entities_speech_id",
        table_name="speeches_transcripts_entities",
    )
    op.drop_index(
        op.f("ix_speeches_transcripts_entities_id"),
        table_name="speeches_transcripts_entities",
    )
    op.drop_table("speeches_transcripts_entities")
    op.drop_index(
        "ix_speeches_transcripts_keywords_speech_id",
        table_name="speeches_transcripts_keywords",
    )
    op.drop_index(
        op.f("ix_speeches_transcripts_keywords_id"),
        table_name="speeches_transcripts_keywords",
    )
    op.drop_table("speeches_transcripts_keywords")
    # ### end Alembic commands ###
