#
# Arquivo de configuração padrão do Alembic.
#
# Mais detalhes: https://alembic.sqlalchemy.org/en/latest/tutorial.html
#

[alembic]
# Caminho relativo para os scripts de migração.
script_location = migrations

# URL do banco utilizada quando a env var DATABASE_URL não estiver definida.
sqlalchemy.url = sqlite:///./mamute.db

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %Y-%m-%d %H:%M:%S